
export const personConstants = {
    FETCH_PEOPLE: 'FETCH_PEOPLE',
    FETCH_PEOPLE_PENDING: 'FETCH_PEOPLE_PENDING',
    FETCH_PEOPLE_SUCCESS: 'FETCH_PEOPLE_SUCCESS',
    FETCH_PEOPLE_FAILURE: 'FETCH_PEOPLE_FAILURE',

    //this is an alias, does the same
    SAVE_FETCHED: 'ADD_PERSON_SUCCESS',

    ADD_PERSON: 'ADD_PERSON',
    ADD_PERSON_PENDING: 'ADD_PERSON_PENDING',
    ADD_PERSON_SUCCESS: 'ADD_PERSON_SUCCESS',
    ADD_PERSON_FAILURE: 'ADD_PERSON_FAILURE',

    UPDATE_PERSON: 'UPDATE_PERSON',
    UPDATE_PERSON_SUCCESS: 'UPDATE_PERSON_SUCCESS',
    UPDATE_PERSON_PENDING: 'UPDATE_PERSON_PENDING',
    UPDATE_PERSON_FAILURE: 'UPDATE_PERSON_FAILURE',

    DELETE_PERSON: 'DELETE_PERSON',
    DELETE_PERSON_SUCCESS: 'DELETE_PERSON_SUCCESS',
    DELETE_PERSON_PENDING: 'DELETE_PERSON_PENDING',
    DELETE_PERSON_FAILURE: 'DELETE_PERSON_FAILURE',
};

export type FETCH_PEOPLE = typeof personConstants.FETCH_PEOPLE;
export type FETCH_PEOPLE_PENDING = typeof personConstants.FETCH_PEOPLE_PENDING;
export type FETCH_PEOPLE_SUCCESS = typeof personConstants.FETCH_PEOPLE_SUCCESS;
export type FETCH_PEOPLE_FAILURE = typeof personConstants.FETCH_PEOPLE_FAILURE;

export type FETCH_PEOPLE_STATUS = FETCH_PEOPLE_PENDING | FETCH_PEOPLE_SUCCESS | FETCH_PEOPLE_FAILURE;

export type SAVE_FETCHED = typeof personConstants.SAVE_FETCHED;

export type ADD_PERSON = typeof personConstants.ADD_PERSON;
export type ADD_PERSON_PENDING = typeof personConstants.ADD_PERSON_PENDING;
export type ADD_PERSON_SUCCESS = typeof personConstants.ADD_PERSON_SUCCESS;
export type ADD_PERSON_FAILURE = typeof personConstants.ADD_PERSON_FAILURE;
export type ADD_PERSON_STATUS = ADD_PERSON_PENDING | ADD_PERSON_SUCCESS | ADD_PERSON_FAILURE;

export type UPDATE_PERSON = typeof personConstants.UPDATE_PERSON;
export type UPDATE_PERSON_PENDING = typeof personConstants.UPDATE_PERSON_PENDING;
export type UPDATE_PERSON_SUCCESS = typeof personConstants.UPDATE_PERSON_SUCCESS;
export type UPDATE_PERSON_FAILURE = typeof personConstants.UPDATE_PERSON_FAILURE;
export type UPDATE_PERSON_STATUS = UPDATE_PERSON_PENDING | UPDATE_PERSON_SUCCESS | UPDATE_PERSON_FAILURE;

export type DELETE_PERSON = typeof personConstants.DELETE_PERSON;
export type DELETE_PERSON_PENDING = typeof personConstants.DELETE_PERSON_PENDING;
export type DELETE_PERSON_SUCCESS = typeof personConstants.DELETE_PERSON_SUCCESS;
export type DELETE_PERSON_FAILURE = typeof personConstants.DELETE_PERSON_FAILURE;
export type DELETE_PERSON_STATUS = DELETE_PERSON_PENDING | DELETE_PERSON_SUCCESS | DELETE_PERSON_FAILURE;