
export const personConstants = {
    FETCH_PEOPLE: 'FETCH_PEOPLE',
    FETCH_PEOPLE_PENDING: 'FETCH_PEOPLE_PENDING',
    FETCH_PEOPLE_SUCCESS: 'FETCH_PEOPLE_SUCCESS',
    FETCH_PEOPLE_FAILURE: 'FETCH_PEOPLE_FAILURE',

    SAVE_FETCHED: 'SAVE_FETCHED',

    ADD_PERSON: 'ADD_PERSON',
    ADD_PERSON_PENDING: 'ADD_PERSON_PENDING',
    ADD_PERSON_SUCCESS: 'ADD_PERSON_SUCCESS',
    ADD_PERSON_FAILURE: 'ADD_PERSON_FAILURE',
};

export type FETCH_PEOPLE = typeof personConstants.FETCH_PEOPLE;
export type FETCH_PEOPLE_PENDING = typeof personConstants.FETCH_PEOPLE_PENDING;
export type FETCH_PEOPLE_SUCCESS = typeof personConstants.FETCH_PEOPLE_SUCCESS;
export type FETCH_PEOPLE_FAILURE = typeof personConstants.FETCH_PEOPLE_FAILURE;

export type FETCH_PEOPLE_STATUS = FETCH_PEOPLE_PENDING | FETCH_PEOPLE_SUCCESS | FETCH_PEOPLE_FAILURE;

export type SAVE_FETCHED = typeof personConstants.SAVE_FETCHED;

export type ADD_PERSON = typeof personConstants.ADD_PERSON;
export type ADD_PERSON_PENDING = typeof personConstants.ADD_PERSON_PENDING;
export type ADD_PERSON_SUCCESS = typeof personConstants.ADD_PERSON_SUCCESS;
export type ADD_PERSON_FAILURE = typeof personConstants.ADD_PERSON_FAILURE;

export type ADD_PERSON_STATUS = ADD_PERSON_PENDING | ADD_PERSON_SUCCESS | ADD_PERSON_FAILURE;