export const photoConstants = {
    FETCH_PHOTOS: 'FETCH_PHOTOS',
    FETCH_PHOTOS_PENDING: 'FETCH_PHOTOS_PENDING',
    FETCH_PHOTOS_SUCCESS: 'FETCH_PHOTOS_SUCCESS',
    FETCH_PHOTOS_FAILURE: 'FETCH_PHOTOS_FAILURE',

    ADD_PHOTO: 'ADD_PHOTO',
    ADD_PHOTO_PENDING: 'ADD_PHOTO_PENDING',
    ADD_PHOTO_SUCCESS: 'ADD_PHOTO_SUCCESS',
    ADD_PHOTO_FAILURE: 'ADD_PHOTO_FAILURE',

    UPDATE_PHOTO: 'UPDATE_PHOTO',
    UPDATE_PHOTO_SUCCESS: 'UPDATE_PHOTO_SUCCESS',
    UPDATE_PHOTO_PENDING: 'UPDATE_PHOTO_PENDING',
    UPDATE_PHOTO_FAILURE: 'UPDATE_PHOTO_FAILURE',

    DELETE_PHOTO: 'DELETE_PHOTO',
    DELETE_PHOTO_SUCCESS: 'DELETE_PHOTO_SUCCESS',
    DELETE_PHOTO_PENDING: 'DELETE_PHOTO_PENDING',
    DELETE_PHOTO_FAILURE: 'DELETE_PHOTO_FAILURE',
};

export type FETCH_PHOTOS = typeof photoConstants.FETCH_PHOTOS;
export type FETCH_PHOTOS_PENDING = typeof photoConstants.FETCH_PHOTOS_PENDING;
export type FETCH_PHOTOS_SUCCESS = typeof photoConstants.FETCH_PHOTOS_SUCCESS;
export type FETCH_PHOTOS_FAILURE = typeof photoConstants.FETCH_PHOTOS_FAILURE;
export type FETCH_PHOTOS_STATUS = FETCH_PHOTOS_PENDING | FETCH_PHOTOS_SUCCESS | FETCH_PHOTOS_FAILURE;

export type ADD_PHOTO = typeof photoConstants.ADD_PHOTO;
export type ADD_PHOTO_PENDING = typeof photoConstants.ADD_PHOTO_PENDING;
export type ADD_PHOTO_SUCCESS = typeof photoConstants.ADD_PHOTO_SUCCESS;
export type ADD_PHOTO_FAILURE = typeof photoConstants.ADD_PHOTO_FAILURE;

export type ADD_PHOTO_STATUS = ADD_PHOTO_PENDING | ADD_PHOTO_SUCCESS | ADD_PHOTO_FAILURE;

export type UPDATE_PHOTO = typeof photoConstants.UPDATE_PHOTO;
export type UPDATE_PHOTO_PENDING = typeof photoConstants.UPDATE_PHOTO_PENDING;
export type UPDATE_PHOTO_SUCCESS = typeof photoConstants.UPDATE_PHOTO_SUCCESS;
export type UPDATE_PHOTO_FAILURE = typeof photoConstants.UPDATE_PHOTO_FAILURE;
export type UPDATE_PHOTO_STATUS = UPDATE_PHOTO_PENDING | UPDATE_PHOTO_SUCCESS | UPDATE_PHOTO_FAILURE;

export type DELETE_PHOTO = typeof photoConstants.DELETE_PHOTO;
export type DELETE_PHOTO_PENDING = typeof photoConstants.DELETE_PHOTO_PENDING;
export type DELETE_PHOTO_SUCCESS = typeof photoConstants.DELETE_PHOTO_SUCCESS;
export type DELETE_PHOTO_FAILURE = typeof photoConstants.DELETE_PHOTO_FAILURE;
export type DELETE_PHOTO_STATUS = DELETE_PHOTO_PENDING | DELETE_PHOTO_SUCCESS | DELETE_PHOTO_FAILURE;