
export const storyConstants = {
    FETCH_STORIES: 'FETCH_STORIES',
    FETCH_STORIES_PENDING: 'FETCH_STORIES_PENDING',
    FETCH_STORIES_SUCCESS: 'FETCH_STORIES_SUCCESS',
    FETCH_STORIES_FAILURE: 'FETCH_STORIES_FAILURE'
};

export type FETCH_STORIES = typeof storyConstants.FETCH_STORIES;
export type FETCH_STORIES_SUCCESS = typeof storyConstants.FETCH_STORIES_SUCCESS;
export type FETCH_STORIES_FAILURE = typeof storyConstants.FETCH_STORIES_FAILURE;
export type FETCH_STORIES_PENDING = typeof storyConstants.FETCH_STORIES_PENDING;

export type FETCH_STORIES_STATUS = FETCH_STORIES_PENDING | FETCH_STORIES_SUCCESS | FETCH_STORIES_FAILURE;